### ISSUE TITLE
Unable to purchase a license, all links from within the app do nothing

### ISSUE THREAD

**Issue by fossephate** [FancyWM/fancywm-issues#100]
**Describe the bug**

I'm unable to purchase a license as the link to do so (I assume it's supposed to open a webpage or the ms store) doesn't do anything for me

**To Reproduce**
Click any link in the UWP

**Expected behavior**
Link should open something

**Screenshots**
https://recordit.co/pXAhSYllhi

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 21H2 64-bit

**Additional context**
I suspect this has to do with a registered URI handle not being registered correctly, i.e. say the url to open is microsoftstore::/fancywm/purchase_license but really I'm not sure why this would happen other than something wrong with the registry

if there's a temporary way for me to buy a license while this is fixed let me know
also: I would've used the "contact the developer" link for this but that doesn't work either of course! (I assume it's an email link)

**Comment by veselink1** [comment]
Thanks for reporting. Purchasing is handled by MS code. A Microsoft Store popup window should open. If the Store App is not working or if there is something wrong with the registry, there is nothing I can do from within the app. 

Here are some links that could help (I haven't tried these): 
https://support.microsoft.com/en-gb/account-billing/microsoft-store-doesn-t-open-126a875d-8b72-def1-0af6-d325276a058b#:~:text=If%20you're%20having%20trouble%20launching%20Microsoft%20Store%2C%20here%20are,Windows%20Update%20%3E%20Check%20for%20Updates.

https://answers.microsoft.com/en-us/windows/forum/all/microsoft-store-app-link-not-working/835bd155-b7c6-457e-ae99-9f2fdacd9e7e

The _Open in Text Editor_ button opens the program configuration file in your default text editor, allowing you to save the configuration for moving to another PC.
