### ISSUE TITLE
FancyWM doesn't work with 'Show this window on all desktops' or 'Show windows from this app on all desktops'

### ISSUE THREAD

**Issue by incorrigible7** [FancyWM/fancywm-issues#104]
**Describe the bug**
FancyWM doesn't work with 'Show this window on all desktops' or 'Show windows from this app on all desktops'. Doing so makes it float. 

**To Reproduce**
1. Go to Windows Task View.
2. Right-click target window > 'Show this window on all desktops' or 'Show windows from this app on all desktops'.

**Expected behavior**
Maintain FancyWM behavior across all desktops. I realize this might not be possible without the functionality of stack panels that can hold vertical/horizontal panels. I'll request that feature in its own post. 

**Desktop (please complete the following information):**
 - OS: win10
 - Version 21H2 64-bit

**Comment by veselink1** [comment]
Thanks for the suggestion. I've thought about ways to handle this and ultimately decided that this feature is too complex to implement correctly and so will not be worked on.
