### ISSUE TITLE
Ability to minimize/restore panels as a group

### ISSUE THREAD

**Issue by incorrigible7** [FancyWM/fancywm-issues#108]
**Describe the solution you'd like**
I would like a minimize button on the panel bar. This could also serve as lesser alternative to nesting panels inside stack panels and/or panel groups/layouts for when you don't want to use an additional desktop. 

I just remembered I think I read somewhere that FancyWM does not target minimized windows. Would that mean to say this cannot be implemented?

**Comment by veselink1** [comment]
Thanks for the feature request. Minimized windows go back to their former panel when restored (if that panel still exists). There is no intention to support the exact behaviour that you've described.
