### ISSUE TITLE
Lag when drag fancywm settings

### ISSUE THREAD

**Issue by pc-v2** [FancyWM/fancywm-issues#11]
**Describe the bug**

Fancywm settings lagging while being dragged
happened too with animation being disabled

**To Reproduce**

1. Open FancyWM Settings
2. Drag the settings
3. The lag happens

**Expected behavior**
smooth drag

**Screenshots**
![terst0001-0781](https://user-images.githubusercontent.com/58063311/145328940-a4be4160-9ded-413b-b2c1-59d6fef7efa2.gif)

**Desktop (please complete the following information):**
 - Windows 11 22000.384 x64

**Comment by veselink1** [comment]
Hi, thanks for opening an issue on here. The answers to the following questions will help diagnose this. 
- Have you observed this behaviour with any other applications?
- Does the latest release fix this for you?
- Does it persist if you disable tiling with F11?

**Comment by pc-v2** [comment]
> Hi, thanks for opening an issue on here. The answers to the following questions will help diagnose this.
> 
>     * Have you observed this behaviour with any other applications?
> 
>     * Does the latest release fix this for you?
> 
>     * Does it persist if you disable tiling with F11?

the response now much faster!
