### ISSUE TITLE
keyboard shortcut for full-screen

### ISSUE THREAD

**Issue by paprocki-r** [FancyWM/fancywm-issues#111]
I'm always frustrated when I have to see window in a full-screen

It would be nice to temporarily set a window in full-screen mode with some fancyWM shortcut, i.e. alt+ctrl+spacebar , like a toogle-mode.

Of course I have F11 working well, but it's outside of fancyWM workflow. Also it's too far away to click.

**Comment by jsonMartin** [comment]
I agree, moving from other Tiling Window Mangers, the "Monocle" view is really helpful

**Comment by veselink1** [comment]
Win + Up is a Windows built-in shortcut to maximise a window. Win + Down to restore.

**Comment by paprocki-r** [comment]
> 
Thank you for your answer. Let me just say - brilliant piece of work, it helps with my daily workflow and of course I will get a license soon

Coming back to the topic: when I think about it then yes, win+up is solution to my problem. So the only missing piece would be to define fancyWM shortcut for that, just for consistency. Thank you for your suggestion.

**Comment by veselink1** [comment]
Thanks for the suggestion. I try to stay away from adding features already present in Windows, because that consumes additional bandwidth for me to implement and maintain and increases overall complexity for the end user (too many keybindings to set up).
