### ISSUE TITLE
Trying to tile some windows results in "no active window" error

### ISSUE THREAD

**Issue by dragos240** [FancyWM/fancywm-issues#112]
**Describe the bug**

When trying to tile some windows, I get "no active window". An example is KeePassXC.

**To Reproduce**

1. Open KeePassXC (what I'm using for testing) window
2. Press the activation combo (shift + win), then `v` to vertical tile
3. Get the error "no focused window"

**Expected behavior**

I expected the active window of KeePassXC to tile with the rest of my programs (might apply to other programs, but not sure)

**Screenshots**

![Screenshot 2022-07-17 054024](https://user-images.githubusercontent.com/704081/179392619-a0355055-ee4d-4623-9893-2937c0590b7e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 21H2 64-bit

**Additional context**

Nothing else I can think of

**Comment by dragos240** [comment]
Fixed this by enabling "open in administrator mode". It would be nice for there to be an entry in the wiki if someone gets this error.

Leaving this open so the dev can see it.

**Comment by veselink1** [comment]
Wiki updated. Thanks.
