### ISSUE TITLE
Closing FancyWM doesn't fully close the program

### ISSUE THREAD

**Issue by dragos240** [FancyWM/fancywm-issues#113]
**Describe the bug**

Attempting to close FancyWM will not completely close the program. I need to go to the app settings and click "terminate" to fix it.

**To Reproduce**

1. Open FancyWM
2. Attempt to close FancyWM via the system tray icon
3. The dialog box containing "Settings, About, Quit" will persist and opening it again yields an error saying another instance is already running.

**Expected behavior**

FancyWM closes completely.

**Screenshots**

![Screenshot 2022-07-17 055646](https://user-images.githubusercontent.com/704081/179393168-a6be4b5f-0ee9-4988-a80d-6af7d46fa528.png)

(See bottom right corner of screenshot)

**Desktop (please complete the following information):**

 - OS: Windows 10
- Version: 21H2 64-bit

**Additional context**

Nothing else

**Comment by incorrigible7** [comment]
I dunno if it was still visible in taskmgr after not fully closing in the past, but it's currently not visible on the list unless you try to re-open it and leave the 'already running' exception window open. Just thought I'd add my observations to the ticket. 

![before](https://user-images.githubusercontent.com/108477484/180886901-bb348894-f048-46e9-a857-daf65d40d3b2.jpg)
![after](https://user-images.githubusercontent.com/108477484/180886915-e2d7f74a-7e71-42db-8ad6-70d3572b4d4c.jpg)

**Comment by veselink1** [comment]
Fixed in v2.8.1. Thanks for reporting.
