### ISSUE TITLE
Resize the window as in any mod [ vertical , horizontal , or  main window ]

### ISSUE THREAD

**Issue by omaru-ok** [FancyWM/fancywm-issues#114]
**Is your feature request related to a problem? Please describe.**
 its not Possibel to resize a window or panel . the way i want . or i want more power .over resizing .  such as spaming everytime keybinds to resize is frustrating  coz , resizing is the one of the thing i do most 

**Describe the solution you'd like**
give option to resize any window.  they way we want . and some what of keybinds solution   for the pressing of keybinds many times for acquired size     as  we  need to press  ']'  for increaeing the  width of panels but for desired size we need to do it many times . hope ur getting what i mean 🥺    
**Describe alternatives you've considered**
well i dont know any alternative 😩 

**Additional context**
sorry for bad english 🙏

**Comment by veselink1** [comment]
Direct hotkeys can do what you're looking for. 

![image](https://user-images.githubusercontent.com/12015256/183299447-721621ce-7b35-42cc-a860-a27fad3a7942.png)

**Comment by omaru-ok** [comment]
no .

we  have to press it eveytime 

we need something like sticy keys to key?
