### ISSUE TITLE
Incompatible with StartAllBack

### ISSUE THREAD

**Issue by chixing** [FancyWM/fancywm-issues#117]
**Describe the bug**
* Default windows 11 taskbar is awful
* StartAllBack is a program to fix that
* FancyVM incorrectly uses taskbar space when StartAllBack is running

**To Reproduce**
1. Run FancyVM with StartAllBack together

**Screenshots**
* Notice the taskbar is partially hidden

![fancyvm issue](https://user-images.githubusercontent.com/2783458/180693293-fcc480b9-49d8-4ea0-a68c-528c9f52c29a.png)

**Desktop (please complete the following information):**
 - Windows 11

**Suggestion**
- Perhaps allow user to change bottom padding size?

**Comment by veselink1** [comment]
FancyWM reads the 'padding' value from the Windows function `GetMonitorInfoEx`. Sorry, but I do not use StartAllBack and will not be supporting third-party Windows extensions in general.
