### ISSUE TITLE
Changing focus from a container to an adjacent one should stick to the already visible window

### ISSUE THREAD

**Issue by sim590** [FancyWM/fancywm-issues#123]
**Is your feature request related to a problem? Please describe.**

Let's say I have the following layout:

              v
             / \
            /   \
           /     \
          /       \
         s        w3
        / \        ^
       /   \
      /     \
     /       \
    w1       w2

where:

* `v`, `s` respectively indicate a vertical split and a stack tile.
* `w1`, `w2` and `w3` are windows in the layout
* `^` indicate where the focus is at the start

**Describe the solution you'd like**

Everything steps here are performed on the keyboard.

1. If I start on `w2` and then focus `w1` (on the left), I see `w1`.
2. Then making my way down to `w3`, I see on my screen `w1` and `w3`.
3. When going back up, I would expect to get on `w1`, but I end up on `w2`.

I think that what FancyWM is doing is focusing the nearest node in the other
container from the poin where I'm coming from. However, that is not the most
natural thing to do. Indeed, if I last focused `w1` to go down to `w3`, it's
because I wanted to see them both on my screen at the same time. If I want to
focus back `w1`, I don't want to go to `w2` before ending up on `w1`. It's
really annoying.

**Describe alternatives you've considered**

None. I only end up making two steps move instead of one. Using the mouse is not
an option for me since it wouldn't "eliminate" the extra step, but rather trade
it for another extra movement which is the movement of my hand from the keyboard
to the mouse back and forth.

**Additional context**

Initial setup, seeing `w2` and `w3`.

![image](https://user-images.githubusercontent.com/4147254/184672849-26473d11-406b-4e6b-a356-e265b4c396cf.png)

1. Going  from `w2` to `w1`

![image](https://user-images.githubusercontent.com/4147254/184673006-ba5540fe-0bb6-4f47-8d07-c635e042949c.png)

2. Going from `w2` to `w3`

![image](https://user-images.githubusercontent.com/4147254/184673138-48a1073a-1b08-4c36-b557-4714d8a81924.png)

3. Going back up and ending up on `w2` instead of `w1` (the last focused window in the stack tile.

![image](https://user-images.githubusercontent.com/4147254/184673266-f6e66d7f-8d42-478a-81a2-8a0e2e2304e0.png)

**Comment by veselink1** [comment]
Hi, thanks for opening a feature request. FancyWM picks the last child of the panel if the navigation direction is left or up, and the first child otherwise. You could use Alt+Tab to switch back to w1 from w3.

**Comment by sim590** [comment]
I would argue that the present state of things creates inconsistency between the mouse setting and the keyboard setting.

When you use the mouse, going back on a previous tile is done by clicking in the tile and what is then focused is the last focused window in that tile. Why make it different on the keyboard? Why would you select a window that is not even visible????? I don't get it.
