### ISSUE TITLE
Windows 11 PC freezing after waking up

### ISSUE THREAD

**Issue by AndresSan6** [FancyWM/fancywm-issues#128]
FancyWM is a very efficient tool that has been making me more productive, unfortunately when my PC sleeps and I have running FancyWM, the PC freezes after waking up and the only solution is hard rebooting my PC.

I am running default configurations and running with admin.

**Comment by veselink1** [comment]
Thanks for reporting. Are you only experiencing this when FancyWM is running as administrator?

**Comment by AndresSan6** [comment]
Hi @veselink1, thanks for asking. I found out that this bug was not caused by FancyWM but from my monitor/GPU drivers.
