### ISSUE TITLE
Window inner padding duplicate

### ISSUE THREAD

**Issue by jwdotpark** [FancyWM/fancywm-issues#13]
**Is your feature request related to a problem? Please describe.**
Inner padding is duplicate as in doubled value compared to window outer padding.

**Describe the solution you'd like**
If adjacent window exists, one of neighbor window shouldn't have inner padding to the other window.

**Additional context**
![image](https://user-images.githubusercontent.com/38537908/145438325-34836010-bc7a-4e3e-bc08-d95b7fbfab70.png)

**Comment by veselink1** [comment]
Thanks for opening this feature request. This should be implemented in v2.2.0, which will come out next week.

![Screenshot (109)](https://user-images.githubusercontent.com/12015256/145587158-5e92564e-93a8-40cf-9e92-1b0b337f335e.png)

**Comment by veselink1** [comment]
Available in v2.2.0. Thanks!
