### ISSUE TITLE
FancyWM and ICUE (Corsair Application)

### ISSUE THREAD

**Issue by KemonoElite** [FancyWM/fancywm-issues#132]
Corsair Relays on active windows for what macros and color lighting is being used for that spcific application.

it would seem ICUE picks up only FancyWM because when I disable FancyWM icue goes back to finding the currently focused window

This may be a Feature Request or may be a issue. But I would love to see FancyWM to work with ICUE

Thanks for your Time

**Comment by veselink1** [comment]
Thanks for reporting. This is because FancyWM creates a fullscreen transparent overlay window to be able to draw on top of other windows. Same cause as #42. I will update this issue in case there is any progress.

**Comment by KemonoElite** [comment]
Thank you for the Reply, I shall look forward to a fix in the future. Thanks for such a great applicaton!

**Comment by veselink1** [comment]
Fixed in v2.10.0.
