### ISSUE TITLE
Unable to use gimp 2.10

### ISSUE THREAD

**Issue by NotNullBool** [FancyWM/fancywm-issues#133]
**Describe the bug**
When I open gimp it will run fine. However gimp will not allow me to select a tool while fancy wm is running it will force me to focus on the tool settings unless I click the title bar then I can select another tool.

**To Reproduce**
1. Open 'Gimp'
2. Select a tool
3. Select another tool

**Expected behavior**
I should be able to select a tool and another tool after without the application not allowing me to

**Screenshots**
[If I use gimp while fancy wm is open](https://i.imgur.com/RzaLF2F.gif)
[Expected behavior](https://i.imgur.com/Mud92I5.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 10.0.22000 build 22000

**Additional context**
Clicking on the title bar fixes the issue temporarily until I select another tool.
I noticed that while fancy wm is open my screen recorder recognizes gimp as fancy wm. I have also noticed that when I was researching the issue it seems the software acts weird depending on the window focus. perhaps the issue has to do with fancy wm taking the focus away from gimp.

**Comment by NotNullBool** [comment]
This appears to be the same issue as 
#42 and #132 I will be closing for now check those issues if you see this

**Comment by veselink1** [comment]
Fixed in v2.10.0.
