### ISSUE TITLE
Resizing shortcut

### ISSUE THREAD

**Issue by jwdotpark** [FancyWM/fancywm-issues#14]
**Is your feature request related to a problem? Please describe.**
Currently resizing can be done only via mouse input.

**Describe the solution you'd like**
Size adjust mode can be nice, just like activation mode. 
Resizing can be done via mod(ctrl/alt/win)+arrow or dev/user's choice if possible. 

**Additional context**
pop_shell handles window size adjust pretty nicely.(https://support.system76.com/articles/pop-keyboard-shortcuts/)

**Comment by rashil2000** [comment]
I would also like this feature. Using mouse in a tiling WM feels weird. Currently, the "Move" and "Swap" functionality do the same thing (at least in my testing):

![image](https://user-images.githubusercontent.com/46838874/146420864-5f819391-56f3-429e-8fa0-975767843551.png)

Perhaps one of them can be changed to resize a window instead?

**Comment by veselink1** [comment]
Thanks for opening this feature request.
I probably need to get Pop OS running and see how they are handling this in pop_shell. It is unclear to me as of yet how *much* the window should be resized and what the hotkeys should map to (does arrow right grow the window to the right only, or symmetrically, likewise does arrow left grow the window to the left or shrink it). It should not be terribly difficult to implement once I've got those figured out. 

@rashil2000 The move and swap commands work identically when the adjacent window belongs to the same panel. But when the adjacent window is in a panel, the move command will move the window to that panel, whereas swap will make the windows exchange places. The attached screen recording shows me swapping notepad with explorer several times (swap left/right), then moving explorer left and then right again (move left/right), which also moves it in and out of the vertical panel. 


https://user-images.githubusercontent.com/12015256/146434923-0decd7cd-56eb-418f-bc98-1bb9e6c9fe95.mp4

**Comment by rashil2000** [comment]
Thank you for the detailed explanation! I was scratching my head as to why they seem to behave the same, I didn't think of inter-panel movement 😅

**Comment by veselink1** [comment]
Implemented in v2.3.0, thanks both!

**Comment by rashil2000** [comment]
Wow, thanks for the quick response!

**Comment by rashil2000** [comment]
I just tried it out, looks amazing!

I don't know if you have it planned already, but a setting to specify no. pixels (basically amount) to resize in one go would be great!

**Comment by veselink1** [comment]
That sounds like a good idea for the next release. The resize amount is a fraction of the monitor size (to account for changes in monitor resolution). In general, you do feel that the current value is too small/large?

**Comment by jwdotpark** [comment]
>  It is unclear to me as of yet how much the window should be resized and what the hotkeys should map to (does arrow right grow the window to the right only, or symmetrically, likewise does arrow left grow the window to the left or shrink it). It should not be terribly difficult to implement once I've got those figured out.

Sorry to chime in late, probably the best way to handle resizing would be continuous mode, e.g. changing the size of the window constantly while the arrow key or some modifier is pressed down. (not sure it would be width/height pixel++ counter or some equivalent.. :D) I think that's a pretty intuitive way to handle the resizing but I gotta say the current option we have is pretty good, though sometimes it needs a multiple activation mode. 

Btw, thanks for the fantastic update! it seems only gets better with updates :)

**Comment by veselink1** [comment]
Hi. I'm glad you're enjoying it. Thanks for the suggestion, I will consider it for a future release.

**Comment by rashil2000** [comment]
> That sounds like a good idea for the next release. The resize amount is a fraction of the monitor size (to account for changes in monitor resolution). In general, you do feel that the current value is too small/large?

See below in my screen (1920x1080):

![cmd2](https://user-images.githubusercontent.com/46838874/146961115-3fe6e3ec-ace9-4d91-8bc2-53176929315c.gif)

The amount seems slightly big to me.

I also agree with @jwdotpark that a continuous mode would be a better option to implement here, which can in turn be configured as to how much the window resizes on each keystroke.
