### ISSUE TITLE
Focused window reminder

### ISSUE THREAD

**Issue by veselink1** [FancyWM/fancywm-issues#15]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have some visual reminder about which window is focused. 

**Describe the solution you'd like**
Highlight the focused window during activation mode.

**Describe alternatives you've considered**
Alternatively, a persistent coloured border around the focused window might also be helpful. 

**Additional context**
This is a feature request from Reddit.

**Comment by veselink1** [comment]
Current status:

https://user-images.githubusercontent.com/12015256/145588704-334bf2b3-7d9e-447d-92c8-1a4a535d3982.mp4

**Comment by jwdotpark** [comment]
> 

This looks fantasstic!!

**Comment by veselink1** [comment]
Available in v2.2.0. Thanks!
