### ISSUE TITLE
Documentation for settings.json

### ISSUE THREAD

**Issue by brendonscript** [FancyWM/fancywm-issues#16]
**Describe the solution you'd like**
Documentation for using the settings.json

**Additional context**
I would like to be able to sync my settings but I am not sure of the schema for the settings file.

**Comment by veselink1** [comment]
Hi, thanks for opening a feature request. Please help me understand the use case here. 
How would a JSON schema help with syncing the settings.json?

**Comment by rashil2000** [comment]
Hey @veselink1! Slightly off-topic, but where is this file located? Clicking on "Open in text editor" in _General_ tab does not do anything for me.

**Comment by veselink1** [comment]
@rashil2000 Thank you for informing me of this. "Open in text editor" *should* open `%appdata%/fancywm/settings.json` in the system's default text editor. Please, check that you can open the file manually to verify that your default editor is working properly.

**Comment by rashil2000** [comment]
There is no folder named `fancywm` in my PC (checked both AppData/Local and AppData/Roaming).

(I have installed through Store)

**Comment by rashil2000** [comment]
Right, thanks, I totally forgot Store apps store data in %LocalAppData%\Packages
