### ISSUE TITLE
Adjust panel font and height independently

### ISSUE THREAD

**Issue by bertenvdb** [FancyWM/fancywm-issues#17]
I find the default panel height a bit too small to my taste and also dislike the lack of spacing around the window titles a bit. 
If I increase panel height, the font of the window titles also increase, which looks a bit akward and ugly.
I'd like to have the font size of the window titles the same as the widow titles of the windows themself. E.g. if you look at the screenshot, I'd like to have 'FancyWM Settings' in the panel tab equally sized as 'FancyWM Settings' in the window itself.

In the Settings>Interface section, add a slider control 'Panel font'. This way, I can set my panel height to 22 and the font for the window titles to e.g. 12. By doing this, the widow titles also won't look jammed in there because theu would have a bit of spacing around them.

An alternative solution would be to decouple the Panel Height setting from the font size and always use the font size the OS uses for it's window titles.

![image](https://user-images.githubusercontent.com/1568251/146159466-60180439-7b89-4038-814b-b328091c4144.png)

BTW, awesome project. Most software takes a week or so for me to decide wether I want to buy a license. FancyWM took less than 5 minutes 😁

**Comment by veselink1** [comment]
Implemented in v2.3.0, thanks!
