### ISSUE TITLE
Incorrect scaling when opening minimized application using multiple monitors

### ISSUE THREAD

**Issue by ignacevau** [FancyWM/fancywm-issues#21]
**Describe the bug**
When using 2 monitors (extended mode) with different scaling settings in Windows display settings, after opening a minimized application, it doesn't open up with correct scaling.

**To Reproduce**
1. Setup 2 extended displays with different scaling settings, for example main display 100% scaling and second display 125% scaling. (In case it matters I used top-bottom layout, with main display on top).
2. Open any application on the main display, for example "File Explorer". 
3. Minimize the application.
4. Open the application again by clicking the icon in the taskbar.
5. The application is not scaled correctly (window size), after refreshing the FancyWM layout / rescaling the window / moving the window, the window scaling is corrected.

**Expected behavior**
The application opens with a correct scaling.

**Screenshots**
Result:
![Screenshot (5)](https://user-images.githubusercontent.com/34870627/147652994-51ec7829-3584-4577-a155-c57865468da8.png)
Expected:
![Screenshot (6)](https://user-images.githubusercontent.com/34870627/147653026-451e709c-4234-499f-811b-d9c2fb177aa5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Home Edition)
 - Version: 10.0.22000

**Additional context**
The word *scaling* probably causes confusion here so just to clarify; With the scaling of the application, I mean the window size (and only the window size). With the scaling of the display, I mean the "scale" settings in the Windows "Scale and Layout" settings under "Display".

**Comment by ignacevau** [comment]
Update: 
I suspect this is caused by the applications opening on the wrong display. 
On the exact same setup as above, when opening a application that was minimized on the second display, it opens on the main display. 
When opening and application that was minimized on the main display, it opens on the second display and immediately moves to the main display, but when the window is refocused, it flickers on the second display + the windows on the second display respond to the window.

Is it possible that when opening an application, it is opened on the wrong display?

**Comment by NylonDiamond** [comment]
I'm having a similar issue. Cycling a window between different monitors always ends up making the window an odd size. Manually grabbing the window will resize it properly again. FancyWM thinks the window is on a different monitor, as mentioned above. Here is a screenshot of me using the hotkey to move the window from a 1080p screen to a 2k screen. 
 
![image](https://user-images.githubusercontent.com/19392284/148673692-6e06890c-5305-41fa-9916-becc58a9e029.png)

**Comment by veselink1** [comment]
Thank you both for reporting this. Just a quick update: I believe I have narrowed down and fixed what is causing this. It is still in certification by Microsoft (mandatory for all updates, takes ~3 workdays). 

I will update this again once v2.3.5 is published.

**Comment by veselink1** [comment]
v2.3.5 is now in the Microsoft Store 🎉. Hopefully, it fixes the bug nicely. I will keep this issue open until that is confirmed.

**Comment by NylonDiamond** [comment]
V2.3.5 didn't fix it for me. Here is a gif of the issue. Moving between monitors eventually messes up window size : 
![output](https://user-images.githubusercontent.com/19392284/149195616-bc3a8d1a-cd35-429a-b776-5a029c7bfde7.gif)

**Comment by veselink1** [comment]
@NylonDiamond Thanks for sharing. Apologies, I was only referring to the issue with minimized windows (the one that is hopefully fixed). This appears to be a separate bug. But may I ask how you move the window between monitors. I believe moving windows between monitors with the mouse works fine, but you appear to be using a hotkey which I am not familiar with.

**Comment by NylonDiamond** [comment]
Oh. My bad. Yes, the mouse works fine. I'm using the default shortcut shift win left/right to move it. Maybe a new issue should be created.

**Comment by ignacevau** [comment]
The new version 2.3.5 fixed it, thanks!
@NylonDiamond seems to have a different issue, so you could probably close this issue as the original one was resolved and create a separate one for moving the windows to different monitors.

**Comment by veselink1** [comment]
Wonderful. I will close this now.

**Comment by veselink1** [comment]
@NylonDiamond I have opened #23 and used the information and gif you provided. I hope that's okay. Tell me if you would like any of that removed.

**Comment by NylonDiamond** [comment]
Looks good to me, thanks!
