### ISSUE TITLE
Fullscreen resets resized width for window.

### ISSUE THREAD

**Issue by marcusyqy** [FancyWM/fancywm-issues#26]
**Describe the bug**
When putting a video on full-screen, if the window was currently adjusted to a certain width, it will reset to half of the computer screen.

**To Reproduce**
1. Open `FancyWM` and two windows of your choice.
2. Resize first window to a larger/smaller width.
3. Enable full screen for first window (double click window or watch video in fullscreen).
4. See that the window resets to half of the width again.

**Expected behavior**
The windows layout should persist. Width should not be reset.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19044 Build 19044

**Comment by veselink1** [comment]
Should be fixed in v2.4.0 available now.
