### ISSUE TITLE
Fullscreen Application Pushed Back

### ISSUE THREAD

**Issue by remiteeple** [FancyWM/fancywm-issues#29]
**Describe the bug**
On focus change to a windowed application all other windowed applications are pulled to the foreground while full screen apps are pulled to the background while the full screen application is pushed to the background.

**To Reproduce**
1. Open at least one windowed application on monitor 1 and 2.
2. Ensure both applications are properly managed by FancyWM.
3. Open full screen application on monitor 1.
4. Click windowed application on monitor 2.
The windowed application on monitor 1 will be pulled to the foreground, and the full screen application will be pushed back.

**Expected behavior**
Fullscreen application on monitor that isn't being interacted with should remain in foreground.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2 64bit

**Comment by veselink1** [comment]
Thanks for reporting. Fixed in the latest version available now in the Microsoft Store.

**Comment by remiteeple** [comment]
Just tested and can confirm that this issue is fixed!
