### ISSUE TITLE
Turning off FancyWm bugs focus display 

### ISSUE THREAD

**Issue by mataslib** [FancyWM/fancywm-issues#33]
**Describe the bug**
Turning off FancyWm bugs focus display 

**To Reproduce**
1. Open VScode
2. Shift+win -> F11
3. Focused window display doesn't dissappear, it's stucked

**Expected behavior**
Focus display is not visible

**Screenshots**
![image](https://user-images.githubusercontent.com/5154014/151509655-d79b054b-d1eb-4d8c-9be8-6004073307d0.png)

**Desktop (please complete the following information):**
Win11

**Comment by veselink1** [comment]
Fixed in v2.6.0.
