### ISSUE TITLE
Question: Where is the changelog / What's New?

### ISSUE THREAD

**Issue by riotrah** [FancyWM/fancywm-issues#35]
**Is your feature request related to a problem? Please describe.**
I just wanna know what new things you've cooked up! I bookmark this repo and check occasionally because I'm passionate about this project even outside of my personal use as a customer, and so similarly I wanna know what you've been up to.

**Describe the solution you'd like**
Maybe it already exists and I'm stupid, but I've tried looking at your reddit, this repo and in-app, and don't see anything like a changelog. It could be anywhere, as long as it's linked to in-app!

**Describe alternatives you've considered**
Reading every single comment you leave in these issues to guess what went into a recent release lol.

**Comment by veselink1** [comment]
Thanks for your interest. The changelog is available through the Microsoft Store (app only). As there is a character limit on the changelog field, only the last couple of versions are visible at any time.

I'll see if I can make the full changelog available somewhere.

**Comment by veselink1** [comment]
Changelog is now available on GitHub as well: https://github.com/FancyWM/fancywm-issues/blob/main/CHANGELOG.md
