### ISSUE TITLE
Floating windows not being saved

### ISSUE THREAD

**Issue by nblackburn** [FancyWM/fancywm-issues#37]
**Describe the bug**
I set some windows to always appear as floating and it seems to get wiped out not long after applying those changes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Settings
2. Navigate to "Rules"
3. Type in some windows to float
4. Click "Apply Changes"

**Expected behaviour**
Should save my preferences

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 21H2

**Comment by veselink1** [comment]
Fixed in the lastest release.
