### ISSUE TITLE
Sub-menu for "float window" button (always float)

### ISSUE THREAD

**Issue by nblackburn** [FancyWM/fancywm-issues#38]
**Is your feature request related to a problem? Please describe.**
Add a sub-menu to the "Float Window" button which can be accessed by right-clicking the button. Left clicking behaves as it does currently.

**Describe the solution you'd like**
When right-clicking the "Float Window" button, a menu is shown with the following options...

- Float Window (Same as left click)
- Always Float Window (updates the rules in settings with the current window)

**Comment by veselink1** [comment]
Available in the latest release.
