### ISSUE TITLE
Rules not honored in settings.

### ISSUE THREAD

**Issue by adrynalyne** [FancyWM/fancywm-issues#40]
**Describe the bug**
Floating Windows rules do not apply/work.

**To Reproduce**
1. Open FancyWM settings.
2. Go to Rules.
2. Add application by name, excluding extension.
3. Click Apply
4. Open or re-open rule-related application.
5. FancyWM will manage the application and tile it.
6. Reboot.
7. FancyWM will manage the application and tile it.

A second method:
1. Open FancyWM settings.
2. Go to Rules.
3. Remove Taskmgr.
4. Click Apply.
5.  Open/re-open Task Manager.
6. Task Manager will still be a floating window.
7. Reboot.
8. FancyWM will not manage the application and tile it.

**Expected behavior**
To exclude specified applications from being tiled.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22000.469

**Additional context**
App version 2.4.1.0

**Comment by veselink1** [comment]
Should be fixed in v2.5.0 now available.

**Comment by adrynalyne** [comment]
Can confirm. 

Thanks!
