### ISSUE TITLE
Support Win Shift S Screenshot Window Capture

### ISSUE THREAD

**Issue by pc-v2** [FancyWM/fancywm-issues#42]
**Is your feature request related to a problem? Please describe.**
I can't capture screenshot per window basis as fancywm took all area to screenshot

**Describe the solution you'd like**
Abilty to use screenshot window capture

![image](https://user-images.githubusercontent.com/58063311/152188929-94ac8973-f600-406b-ba45-0c634c78980a.png)

**Comment by veselink1** [comment]
I wasn't aware of that behaviour, thanks for reporting!

**Comment by veselink1** [comment]
Fixed in v2.10.0.
