### ISSUE TITLE
Focus assist get's enabled by itself if the automatic rule "When I'm using an app in fullscreen" is enabled

### ISSUE THREAD

**Issue by HarumiAme** [FancyWM/fancywm-issues#46]
**Describe the bug**
While the automatic rule "When I'm using an app in fullscreen" is enabled (and FancyWM is running), focus assist gets enabled automatically in these circumstances:
1) When there is at least one window open and you click anywhere in the task bar (only if one or more of them is being managed by FancyWM).
2) While every window is minimized .

**To Reproduce**
1. Enable the automatic rule "When I'm using an app in fullscreen" under Settings > System > Focus assist .
2. Open at least one program that gets tiled by FancyWM.
3. Click on an empty space in the taskbar. Focus assist is then enabled.
4. Clicking back on a window disables focus assist.
or:
1. Enable the automatic rule "When I'm using an app in fullscreen" under Settings > System > Focus assist .
2. Minimize every open window (either doing that manually or pressing Win + D works).
3. Focus assist is then enabled, and can only be disabled either by doing it manually or opening a window.

**Expected behavior**
Focus assist should not get enabled by using FancyWM and having that rule enabled if no window is in fullscreen.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 21H2 64-bit

**Additional context**
The steps above work every time as described, but sometimes focus assist get's enabled while doing other things like opening and closing applications, and when that happens, clicking on opened windows does not disable focus assist. I haven't been able to reproduce that consistently though.

**Comment by veselink1** [comment]
This has been fixed in v2.6.0.

**Comment by HarumiAme** [comment]
Confirmed, thanks a lot!
