### ISSUE TITLE
Release as an EXE

### ISSUE THREAD

**Issue by SuperSaiyanBlue** [FancyWM/fancywm-issues#49]
**Is your feature request related to a problem? Please describe.**
I am frustrated by the fact that windows 10 ameliorated (or people without the ability to use windows store) cannot install this at all. 

**Describe the solution you'd like**
Please release an exe install.

**Describe alternatives you've considered**
I don't want to have to reinstall windows, install your tool, and then spend 8 hours manually re-ameliorating my system, copying over data, and then re-encrypting my HDD, for proper window management. 

**Additional context**
I sent you a message on the gitter chat like 2 weeks ago.

**Comment by veselink1** [comment]
Hi, thanks for opening a feature request. 

For the time being, FancyWM only supports unmodified stable releases of Windows 10 (after 1809) and 11. A standalone release is not under consideration, as that would require considerable and continued engineering effort to distribute, license, and maintain, sorry.

**Comment by SuperSaiyanBlue** [comment]
No, it wouldn't take that much effort you lazy nigger. You can just say "No"
