### ISSUE TITLE
Direct hotkeys cannot be mapped to Alt + letter/number. (Locks to alt key instead)

### ISSUE THREAD

**Issue by Huray-hub** [FancyWM/fancywm-issues#52]
**To Reproduce**
FancyWM settings -> keybinds -> try map alt+1. It adds Alt instead.

**Expected behavior**
Ability to map alt only combinations

 - OS: Windows 11
 - Version: Latest

**Comment by veselink1** [comment]
Thanks for reporting!

**Comment by veselink1** [comment]
Fixed in v2.6.1. Thanks.
