### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by rcronk** [FancyWM/fancywm-issues#53]
**Describe the bug**
I have two monitors.  One is lower resolution at 100% scaling.  The other is 4k at 150% scaling.  I leave my computer on for days or weeks at a time without rebooting.  When I start fancywm, it takes up about 300MB of RAM.  Overnight, the memory usage increased to about 8GB of RAM.  The computer was sluggish because it was swapping to disk.  I have 16GB of RAM and had Outlook, Teams, and several tabs in Chrome open overnight.  (I've also seen fancywm exit overnight, so perhaps it died because of OOM or crash.  I got a crash dump that it uploaded to you too.  Not sure if these are related or not.)

**To Reproduce**
Open several windows, perhaps on two monitors, let it run overnight or for a few days, observe the RAM usage increase over time.

**Expected behavior**
I expect the RAM usage to remain constant over time.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10 Home
 - 20H2 19042.1526 64-bit

**Additional context**
N/A

**Comment by rcronk** [comment]
I love this window manager, by the way.  Thanks for creating it.

**Comment by veselink1** [comment]
Thanks for reporting. Very concerning. I have not seen this happen before, so I might need more information when I start looking into this. The memory usage on startup seems excessive as well.

**Comment by rcronk** [comment]
1. When I came in this morning, it didn't exit.  It just sat there at 8GB RAM usage in task manager.
2. It's not huge, but it is the log from last night overnight.  It has a repeated error throughout the night, so that error path might have the leak in it?  Here's the error that repeated many times through the night with no computer use - it was at the lock screen:

[WRN] New active display Win32Display { \\.\DISPLAY2 } is not associated with a tiling service!


[fancywm-crash-20220211T093139.log](https://github.com/FancyWM/fancywm-issues/files/8051561/fancywm-crash-20220211T093139.log)

**Comment by rcronk** [comment]
One more crash from last night - different crash this time, Out of memory:

2022-02-12 20:09:01.724 -07:00 [WRN] New active display Win32Display { \\.\DISPLAY2 } is not associated with a tiling service!
2022-02-12 20:10:12.863 -07:00 [WRN] New active display Win32Display { \\.\DISPLAY2 } is not associated with a tiling service!
2022-02-12 20:11:40.136 -07:00 [WRN] New active display Win32Display { \\.\DISPLAY2 } is not associated with a tiling service!
2022-02-12 20:16:43.069 -07:00 [WRN] New active display Win32Display { \\.\DISPLAY2 } is not associated with a tiling service!
2022-02-12 20:17:47.275 -07:00 [WRN] New active display Win32Display { \\.\DISPLAY2 } is not associated with a tiling service!
2022-02-12 20:18:14.110 -07:00 [FTL] System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

[fancywm-crash-20220212T201814.log](https://github.com/FancyWM/fancywm-issues/files/8056290/fancywm-crash-20220212T201814.log)

**Comment by rcronk** [comment]
Here are a few more crash logs.  Some are similar, some are different.  I'm not certain that these are all releated, but it does seem like my setup is exercising some areas of the code that are useful.  I'll keep posting them since some are different and might give you additional hints to the root cause(s).  Let me know if I can give you any other information that would be helpful.

During the day when I'm using my PC, the window manager is awesome, though!

[fancywm-crash-20220213T144251.log](https://github.com/FancyWM/fancywm-issues/files/8082207/fancywm-crash-20220213T144251.log)

[fancywm-crash-20220215T031350.log](https://github.com/FancyWM/fancywm-issues/files/8082209/fancywm-crash-20220215T031350.log)

[fancywm-crash-20220216T010015.log](https://github.com/FancyWM/fancywm-issues/files/8082212/fancywm-crash-20220216T010015.log)

**Comment by veselink1** [comment]
Thanks. Can you indicate which of the two monitors is set as the primary monitor for the system and whether the monitors turn off automatically when not in use? That should be very helpful.

**Comment by rcronk** [comment]
The left monitor (lower resolution 100% scaling) is primary.  The right monitor (4k resolution "smart" monitor (has internet and can also connect to prime video, hulu, etc.) 200% scaling) is secondary).  The right monitor turns on and off all night perhaps because it's not detecting inactivity properly.

I will run it with the --verbose switch and upload any logs/crashes.

**Comment by rcronk** [comment]
No crash this morning, but the log file is definitely larger and now includes INFO level log lines.  I'll attach it here in case it's useful.

[fancywm.log](https://github.com/FancyWM/fancywm-issues/files/8090563/fancywm.log)

**Comment by rcronk** [comment]
Here's a crash with verbose logging.

[fancywm-crash-20220218T022746.log](https://github.com/FancyWM/fancywm-issues/files/8101011/fancywm-crash-20220218T022746.log)

**Comment by rcronk** [comment]
Here are some more logs.  We'll see if we get another verbose log and crash in the morning.  Hopefully with enough of these you'll see some patterns that could lead you to the issue.

[fancywm-crash-20220218T223555.log](https://github.com/FancyWM/fancywm-issues/files/8114460/fancywm-crash-20220218T223555.log)
[fancywm-crash-20220222T002623.log](https://github.com/FancyWM/fancywm-issues/files/8114461/fancywm-crash-20220222T002623.log)
[fancywm-crash-20220222T002618.log](https://github.com/FancyWM/fancywm-issues/files/8114462/fancywm-crash-20220222T002618.log)

**Comment by veselink1** [comment]
Thanks. I think I found where the memory leak is coming from and will publish an update soon.

I am still don't understand what is causing the `Active display changed` events in the log, when you are not using the machine. It might have to do with the monitor not sleeping properly. In any case, I'd like to get it fixed, if possible. To make it easier, I will add some extra logging around that portion of the code together with the next release. 

Stay tuned, hopefully the memory leak will be fixed for you in v2.6.2 once it's published.

**Comment by rcronk** [comment]
Awesome!  Yeah, the "smart monitor" seems to be using video change detection to put itself to sleep and wake itself back up and so it's probably disconnecting and reconnecting all night long.  Hopefully some additional logging will help you figure it out.  I'll leave the smart monitor settings the same until we have everything you want from this setup and then once we have all the fixes, I'll see if I can disable the "smart" sleeping it keeps doing (which isn't smart at all! :D),

Thanks for your responsiveness!  I love the fancy window manager!

**Comment by rcronk** [comment]
Just for completeness, here's another big log from last night.

[fancywm-crash-20220222T045325.log](https://github.com/FancyWM/fancywm-issues/files/8118533/fancywm-crash-20220222T045325.log)

**Comment by veselink1** [comment]
v2.6.2 is available now.

**Comment by rcronk** [comment]
I ran with 2.6.2 verbose last night and it still crashed with out of memory.  I also noticed last night that it was eating about 7% CPU continuously.  Not sure if that's a different issue or not.  Here's the log from last night.  Hopefully it will shed more light on the issue.

[fancywm-crash-20220223T025645.log](https://github.com/FancyWM/fancywm-issues/files/8125138/fancywm-crash-20220223T025645.log)

**Comment by veselink1** [comment]
I believe I've managed to identify and fix the source of the memory leak. No need for additional logs. Thank you for spending the time to help fix this. 

The 7% CPU could be normal, given that a monitor is switching on/off and the verbose logging. If it persists after v2.6.4, consider opening another issue. 

I will update you once v2.6.4 has passed the Microsoft Store certification.

**Comment by rcronk** [comment]
I left the system for about 20 minutes just now and came back.  It had a crash dialog with an upload option.  It's a different exception, so let me know if you want a different ticket or not once you've looked at the log.  The exception is "[FTL] System.InvalidOperationException: Collection was modified; enumeration operation may not execute."  Log is attached.

[fancywm-crash-20220223T154706.log](https://github.com/FancyWM/fancywm-issues/files/8128505/fancywm-crash-20220223T154706.log)

**Comment by veselink1** [comment]
Should be fixed by v2.6.3 which is in the Store now. Thanks.

**Comment by rcronk** [comment]
I got 2.6.3 installed now.  I'll run it with verbose and see what happens tonight.  Thanks!

**Comment by rcronk** [comment]
Two more crashes.  It seems like the memory leak is not happening in these crashes.  I'll wait until tomorrow morning to make sure that's the case and then I'll close this.  I think I'll open a different issue with these crashes.  It seems like it's during device enumeration, which could also be caused by the smart monitor turning off and on.  I'm glad I have a good setup that can exercise this part of the code so you can harden it, even though it's probably a bit rare.

[fancywm-crash-20220227T174612.log](https://github.com/FancyWM/fancywm-issues/files/8150420/fancywm-crash-20220227T174612.log)
[fancywm-crash-20220227T202554.log](https://github.com/FancyWM/fancywm-issues/files/8150421/fancywm-crash-20220227T202554.log)

**Comment by veselink1** [comment]
You've done more than enough. I've narrowed it down to a race condition between the clean-up code I added to solve the memory leak and the UI refresh. I will upload a fix soon. Thanks a lot.

**Comment by rcronk** [comment]
I got a crash this morning on 2.6.4.0: Collection was modified; enumeration operation may not execute.  This sounds like a locking issue between threads or processes.  Like the collection you're working with is getting modified (by the OS?) while you're working with it, or something like that.  Do you want a new ticket for this?

[fancywm-crash-20220301T075204.log](https://github.com/FancyWM/fancywm-issues/files/8162728/fancywm-crash-20220301T075204.log)

**Comment by rcronk** [comment]
I've not seen any memory issues after the recent changes, so I'll close this as fixed.  Thanks!  I'll create a new ticket with the other issue mentioned above.
