### ISSUE TITLE
Allow less automatic behavior

### ISSUE THREAD

**Issue by bardo84** [FancyWM/fancywm-issues#63]
My usual flow is to have two windows, tiled using dragging to the left and right or by WIN-left and WIN-right. Now connect the borders, so that dragging the line between them resizes both, as opposed to without FancyWM.

I would prefer to apply tiling selectively to a single or all visible windows only.
FancyWM continues screen tiling with all newly opened windows, which can be annoying.

So, default behavior is: adding automatically new windows to tiling, manually opting out by clicking the float symbol. 

I would prefer the opposite: manually adding windows to the tiling.

**Comment by aspidxt** [comment]
It's can be configurable

If you implement layout save/restore feature from #4 it's will be possible to set default group for new windows, for ex I want all new windows appear on center my stack, for now I'd prefer default floating mode (as new windows break laayout and I can't quickly restore it)

**Comment by veselink1** [comment]
Thanks for the feature request. This can be configured by adding a floating rule for all windows (`.*`: dot asterisk) as shown in the screenshot.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/12015256/190996233-d56fb64d-bf5d-4392-b560-a4fae6f32662.png">
