### ISSUE TITLE
Drag & Drop Focus

### ISSUE THREAD

**Issue by remiteeple** [FancyWM/fancywm-issues#65]
**Describe the bug**
When explorer is in the foreground and a file is dragged with the intention of dropping it into a different application explorer will not release its focus.

**To Reproduce**
1. Open Explorer
2. Ensure that the window is sized across your monitor but not Fullscreen.
3. Drag a file and attempt to bring focus to a Fullscreen application behind explorer.

**Expected behavior**
Focus should be released from explorer and instead belong to the currently hovered application for the file dropping.

**Screenshots**
![image](https://user-images.githubusercontent.com/20644236/156222689-6745dab8-86af-4c1f-99cb-5a1ecb56e465.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2 64bit

**Comment by veselink1** [comment]
Thanks for reporting. How do you "attempt to bring to focus" the other window?

**Comment by remiteeple** [comment]
Focus can be gained if the user is currently dragging a file and a new window is hovered with the mouse.  This may not actually be a bug caused by FancyWM.  It could be some Windows 11 funk.

**Comment by veselink1** [comment]
I see. Does it happen when FancyWM is not running?

**Comment by remiteeple** [comment]
Yep, seems to be the wonkiness of Windows 11.
