### ISSUE TITLE
Unable to purchase license

### ISSUE THREAD

**Issue by DeltaForCain** [FancyWM/fancywm-issues#67]
Whenever I click the "purchase" button, a Windows Store window pops up, stays blank, and vanishes after without the possibility of doing anything

I have attached a video, I think it is self-explanatory.

https://user-images.githubusercontent.com/69416780/158008429-97f41229-3c66-46e2-bd43-3f4608601950.mp4

I would love to support this app as it has really made a difference to me!

Edit: The video does not seem to work for me, so I uploaded it [here again](https://imgur.com/qEfXtzo).

**Comment by veselink1** [comment]
Hello, thanks so much for reporting this. I am able to reproduce this consistently when running FancyWM as an Administrator. Please try to *not* run as Administrator, and attempt the purchase again.

**Comment by DeltaForCain** [comment]
Thank you! This solves it. Take this for your fast response ;-)
![image](https://user-images.githubusercontent.com/69416780/158054847-ef3ba920-76e3-423a-9796-886b6aa9bcc3.png)
