### ISSUE TITLE
Show desktop (win+D), Dexpot compatibility, loss of layout

### ISSUE THREAD

**Issue by ngeraks** [FancyWM/fancywm-issues#69]
I am using Dexpot for virtual desktops.
When switching to the second desktop and back the layout is lost and FancyWM repositions all windows to some default setting. 
To me it seems FancyWM should keep track of window positions and switching back to the previous arranged desktop should be loading that. 
As I am writing this I have opened firefox, telegram and FancyWM settings. When pressing win+D a similar issue appears.

**Comment by veselink1** [comment]
Thanks for opening a feature request. "Show desktop (win+D), Dexpot compatibility, loss of layout" This is really several feature requests combined into one. As of v2.9.0, FancyWM has a show desktop feature implemented. Third-party apps such as Dexpot are not officially supported, thanks.
