### ISSUE TITLE
Add keyboard shortcut for minimize all other windows except the active window on a display.

### ISSUE THREAD

**Issue by oulongwen** [FancyWM/fancywm-issues#73]
I love this app! I would love it more if it is possible to add a keyboard shortcut to keep the active window and minimize all other windows on a display. I understand that we can use the "windows + up" key combination to maximize the active window. This is similar to what I am requesting, but not exactly the same. I just prefer to see the padding around the window border.

This function can be found in other tiling window managers. For example: `Grid-Tiling: Toggle Minimize Desktop` in [Kwin Grid-Tiling](https://github.com/lingtjien/Grid-Tiling-Kwin).

**Comment by Zwatotem** [comment]
Just a comment, because I understand you're looking for the keyboard shortcut, but for the time being you can do this with a mouse by shaking the window (works in reverse too).

**Comment by veselink1** [comment]
Thanks for the suggestion. This is actually built-in to Windows. The feature is called Aero Shake and can be toggled by shaking the window or by `Win + Home`!

**Comment by oulongwen** [comment]
> Just a comment, because I understand you're looking for the keyboard shortcut, but for the time being you can do this with a mouse by shaking the window (works in reverse too).

> Thanks for the suggestion. This is actually built-in to Windows. The feature is called Aero Shake and can be toggled by shaking the window or by `Win + Home`!

Thank you both for the reply. However, `Win + Home` and shaking the window minimize all windows on all monitors except for the active window, at least for Windows 10, but what I was looking for is to minimize all windows except for the active window on the current screen only. Is there already a way to do this?
