### ISSUE TITLE
Hotkey to change Windows focus in Stack layout

### ISSUE THREAD

**Issue by haininhhoang94** [FancyWM/fancywm-issues#74]
**Is your feature request related to a problem? Please describe.**
No. This feature is quite simple and doesn't related to any bugs. 
**This feature should have a hotkey to cycle around the stack windows, without using mouse to press the Tab above the stack.**

**Describe the solution you'd like**
This feature should have a hotkey to cycle around the stack windows, without using mouse to press the Tab above the stack.

**Describe alternatives you've considered**
Not exactly an alternative, but this feature is from Amethyst (Mac), which allow a hotkey to cycle windows around in fullscreen layout.
![image](https://user-images.githubusercontent.com/34930708/161702841-e5184b82-9ebc-4cdc-9cef-ff3445ce5ce4.png)

Something like [this](https://github.com/ianyh/Amethyst)

**Additional context**
Not really, since the project is closed source, if possible, you can open part of the source code that handle the Hotkey assign. In my opinion, this project is very promising and worth every penny it demand!

**Comment by veselink1** [comment]
Thanks for opening a feature request. The *Move Focus Left/Right* hotkeys can be used to cycle through the windows in a stack panel. 

![Screenshot 2022-04-06 102422](https://user-images.githubusercontent.com/12015256/161942993-19c5024a-9551-47e9-b224-eee0ef00fe4b.png)

Please confirm that this works for you.

**Comment by haininhhoang94** [comment]
Thanks. It works!

Just one more thing, is there any way that I can cycle around the windows clockwise or counter-clockwise like Amethyst?
