### ISSUE TITLE
Hide the window title bar

### ISSUE THREAD

**Issue by jweickm** [FancyWM/fancywm-issues#79]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem:
When using FancyWM, screen real estate becomes even more important as we are often opening multiple windows at the same time. Especially, when vertically stacking windows, the title bar of each window takes away a lot of the available screen height. Additionally, the window title is already showing up in the panel above (redundant information).

**Describe the solution you'd like**
A solution would be to introduce a toggleable option that allows us to hide the window title bar of each window. Additionally, we could allow for the title bar only when it is the only window open on that screen/desktop.

**Describe alternatives you've considered**

**Additional context**
![fancywm_window_title](https://user-images.githubusercontent.com/57487288/164453228-64bcff4f-a26a-4e5b-bf22-72bf908414d9.png)

**Comment by veselink1** [comment]
Thanks for the feature suggestion! Removing the title bar from the window cannot be implemented portably, and a per-window option/rule would be necessary. Even then, I don't believe it is possible to implement this without the occasional visual "glitch". But more importantly, is not possible to hide the title bar without disrupting the following:
- Window controls (- [] x) will be gone
- Double-click the title bar to maximise will not be available
- Dragging the window will not be possible 

For those reasons, I am going to close this issue.
