### ISSUE TITLE
License Status not updating

### ISSUE THREAD

**Issue by remiteeple** [FancyWM/fancywm-issues#81]
**Describe the bug**
When attempting to activate my license of FancyWM I encounter an error that prevents the activation of the application.  This issue persists when re-installing FancyWM.  While I still get full functionality of the application, I do receive pop-ups telling me to activate my license or purchase a new one, which can be a little annoying.

**To Reproduce**
1. Open FancyWM settings panel.
2. Attempt to activate license.
3. Error PUR-UserAlreadyOwnsContent

**Expected behavior**
The license should be activated.

**Screenshots**
![image](https://user-images.githubusercontent.com/20644236/165551689-8efd1ce3-1a9d-49fb-ba2a-e0036dcdf4ae.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2 64-bit

**Comment by veselink1** [comment]
I'm very sorry about this. A fix is in the works. Thanks.
