### ISSUE TITLE
Add 'Toggle to most recent virtual desktop'

### ISSUE THREAD

**Issue by jbmestelan** [FancyWM/fancywm-issues#90]
Many thanks for FancyWM; it is very useful, even though I would like to suggest adding a feature: the ability to move back to the previously visited virtual desktop. 

Use-case: I like to use several (9) virtual desktops, each containing one or several applications by theme (`1` would be the IDEs, `2` the text editors, `3` the terminals,...). It often happens that I need to shortly visit an other desktop (e.g. to copy content, ...) then come back to the original one. Sure, it is possible to do: `Switch to 3`, then `Switch to 1`. But it is easier on the fingers and on the brain to do: `Switch to 3`, then `Switch back to previous`. Also, this shortcut is very convenient if you repeatedly toggle between two desktops for a given activity.

The use-case above is inspired by XMonad, which has toggleWS: https://hackage.haskell.org/package/xmonad-contrib-0.17.0/docs/XMonad-Actions-CycleWS.html
Thank you for your attention.

**Comment by veselink1** [comment]
Thanks for the feature request. It has been implemented and will be available in the next release.

**Comment by veselink1** [comment]
This is available as of v2.7.0, thanks! https://github.com/FancyWM/fancywm-issues/blob/main/CHANGELOG.md#v270
