### ISSUE TITLE
Do not distinguish between left and right modifiers in keyboard shortcuts

### ISSUE THREAD

**Issue by jweickm** [FancyWM/fancywm-issues#94]
**Is your feature request related to a problem? Please describe.**
When moving windows to others desktops, etc. I prefer to press the right-hand modifiers with my right hand, and then press the numbers 1-5 on the left-hand side of the keyboard with my left hand. Otherwise I prefer using the left-hand modifiers. This is currently not possible as FancyWM allows only one shortcut per action and distinguishes between left- and right-hand modifiers.

**Describe the solution you'd like**
I would like FancyWM to register left and right shift/ctrl/alt/win equally (similar to fancyzones). 

**Describe alternatives you've considered**
I have a programmable keyboard and remapped both my shift/ctrl keys to the left version. However, this seems excessive, not feasible for many people, and leaves me without the right-hand version of those keys on my keyboard.

**Comment by jweickm** [comment]
Glad you like it. I hope it's not too complicated to implement.

**Comment by veselink1** [comment]
This was implemented in v2.7.0, but I forgot to close the issue. Thanks again. 
[CHANGELOG](https://github.com/FancyWM/fancywm-issues/blob/main/CHANGELOG.md#v270)
