### ISSUE TITLE
Closing a window with FancyWM

### ISSUE THREAD

**Issue by sim590** [FancyWM/fancywm-issues#95]
**Is your feature request related to a problem? Please describe.**

Mapping for closing a window. On i3 (on GNU/Linux), I normally use a combination of keys to close the window, but there doesn't seem to be anything possible.

**Describe the solution you'd like**

A keymap option for this would be appreciated. For instance, I would like to press <kbd>ActivationKey</kbd>, <kbd>c</kbd> for <kbd>c</kbd>losing a window.

**Describe alternatives you've considered**

Pressing ALT+F4 which breaks my workflow and finger and wrists placement.

**Comment by sil0o** [comment]
Hi, AutoHotKey can solve your issue.

**Comment by sim590** [comment]
@sil0o: I have not tried, but I trust what you say. Thanks for trying to provide a workaround.

That being said, it's a basic function of a window manager (in GNU/Linux at least) to handle the windows and that implies the closing feature IMO. 

When you accumulate many configurations on the tools you use, it becomes increasingly hard to track if things are not sorted logically and the most logical thing is for FancyWM to handle this, I think.

So for those reasons, I hope that it becomes possible to do this in FancyWM as it is doable in [Workspacer][], [b3][], [win3wm][] and others. Even though all of those window managers suck (Workspacer sucking less than the others), they all provide that functionnality and it is expected.

[Workspacer]: https://github.com/workspacer/workspacer
[b3]: https://github.com/ritschmaster/b3
[win3wm]: https://github.com/McYoloSwagHam/win3wm

**Comment by veselink1** [comment]
Thanks for the feature request. I try to stay away from (re)implementing functionality provided by the OS. As @sil0o mentioned, this is best done with a tool such as AutoHotkey.
