### ISSUE TITLE
Switch focus between multi monitor

### ISSUE THREAD

**Issue by di9eiko0dcikv** [FancyWM/fancywm-issues#98]
Hi! First of all, thank you for making such useful tool!❤

**Is your feature request related to a problem? Please describe.**
I have multi monitor here, i can only switch manually switch the focus of screen by mouse , i haven't found the feature in settings,so i issued it at here.

**Describe the solution you'd like** 
It's will be great if there are support some hotkey for switch focus between different screen

**Describe alternatives you've considered**
Just switch the focus when the specific thermal key is triggered to the window where another screen was activated last time

**Comment by willthong** [comment]
It would make more sense if (like with i3) we could just use the direction of the monitor. So if my focus is on my lower monitor and I try to move focus up, it should do so rather than saying "no adjacent window" as it does at the moment.

**Comment by veselink1** [comment]
This has been implemented as of v2.8.0. Thanks.
[CHANGELOG](https://github.com/FancyWM/fancywm-issues/blob/main/CHANGELOG.md#v280)

**Comment by willthong** [comment]
Thanks @veselink1 - this is better than before but I'd still appreciate the option (saves binding ``F1``-``F10``, and instead you could just bind ``j`` and ``k`` to not only cycle between windows, but also cycle between desktops.

**Comment by willthong** [comment]
This now works for switching between monitors. Thanks very much @veselink1! Only thing missing is that I can't move windows between monitors in the same way (it says "No adjacent window!").
